OFFER=22k
LOOKLIKE=homeboy


all:salry.txt type.txt
	cat salry.txt>>loser.txt ; cat type.txt >> loser.txt
salry.txt:
	echo $(OFFER)>>salry.txt
type.txt:
	echo $(LOOKLIKE)>>type.txt
clean:
	rm *.txt


